[package]
name = "gnosis"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "gnosis_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.28.0", features=["macros"]}
